In [2]:
from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Lambda
from keras.layers import Embedding
from keras.layers import Convolution1D,MaxPooling1D, Flatten
from keras.datasets import imdb
from keras import backend as K
from sklearn.model_selection import train_test_split
import pandas as pd
from keras.utils.np_utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from keras.models import Sequential
from keras.layers import Convolution1D, Dense, Dropout, Flatten, MaxPooling1D
from keras.utils import np_utils
import numpy as np
import h5py
from keras import callbacks
from keras.layers import LSTM, GRU, SimpleRNN, Bidirectional
from keras.callbacks import CSVLogger
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger

In [3]:
traindata = pd.read_csv('/home/ritika/NetworkIntrusionDetection/UNSW-NB15 - CSV Files/a part of training and testing set/UNSW_NB15_training-set.csv')
testdata = pd.read_csv('/home/ritika/NetworkIntrusionDetection/UNSW-NB15 - CSV Files/a part of training and testing set/UNSW_NB15_testing-set.csv')

#traindata=traindata.drop('id',axis=1)
#testdata=testdata.drop('id',axis=1)

from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()

traindata['proto'] = lb_make.fit_transform(traindata['proto'])
traindata['service'] = lb_make.fit_transform(traindata['service'])
traindata['state'] = lb_make.fit_transform(traindata['state'])
traindata['attack_cat'] = lb_make.fit_transform(traindata['attack_cat'])

testdata['proto'] = lb_make.fit_transform(testdata['proto'])
testdata['service'] = lb_make.fit_transform(testdata['service'])
testdata['state'] = lb_make.fit_transform(testdata['state'])
testdata['attack_cat'] = lb_make.fit_transform(testdata['attack_cat'])

X = traindata.iloc[:,1:42]
Y = traindata.iloc[:,-2]
x = testdata.iloc[:,1:42]
y = testdata.iloc[:,-2]

In [4]:
Arr = X.values
arr = x.values

import librosa
Arr_Delta = librosa.feature.delta(Arr)
arr_delta = librosa.feature.delta(arr)

Delta1 = pd.DataFrame(Arr_Delta)
delta1 = pd.DataFrame(arr_delta)

XDelta1 = pd.concat([X, Delta1], axis=1)
xdelta1 = pd.concat([x, delta1], axis=1)

scaler = Normalizer().fit(XDelta1)
XDelta1 = scaler.transform(XDelta1)
scaler = Normalizer().fit(xdelta1)
xdelta1 = scaler.transform(xdelta1)

Y = np.array(Y)
y = np.array(y)

XDelta1 = np.reshape(XDelta1, (XDelta1.shape[0],1,XDelta1.shape[1]))
xdelta1 = np.reshape(xdelta1, (xdelta1.shape[0],1,xdelta1.shape[1]))

lstm_output_size = 70

Y = to_categorical(Y)
y = to_categorical(y)

In [25]:
y.shape

(82332, 10)

In [5]:
model = Sequential()
model.add(LSTM(4,input_dim=82)) 
model.add(Dropout(0.1))
model.add(Dense(10))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

/home/ritika/.virtualenvs/pythree/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  
/home/ritika/.virtualenvs/pythree/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(4, input_shape=(None, 82))`
  


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 4)                 1392      
_________________________________________________________________
dropout_1 (Dropout)          (None, 4)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                50        
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
Total params: 1,442
Trainable params: 1,442
Non-trainable params: 0
_________________________________________________________________


In [6]:
history = model.fit(XDelta1, Y, epochs=200, validation_data=(xdelta1, y))


Train on 175341 samples, validate on 82332 samples
Epoch 1/200
175341/175341 [==============================] - 50s 287us/step - loss: 1.5099 - accuracy: 0.4880 - val_loss: 1.2968 - val_accuracy: 0.6170
Epoch 2/200
175341/175341 [==============================] - 46s 262us/step - loss: 1.4053 - accuracy: 0.5192 - val_loss: 1.2972 - val_accuracy: 0.6176
Epoch 3/200
175341/175341 [==============================] - 48s 272us/step - loss: 1.3916 - accuracy: 0.5270 - val_loss: 1.2912 - val_accuracy: 0.6180
Epoch 4/200
175341/175341 [==============================] - 49s 282us/step - loss: 1.3803 - accuracy: 0.5312 - val_loss: 1.2811 - val_accuracy: 0.6177
Epoch 5/200
175341/175341 [==============================] - 51s 294us/step - loss: 1.3701 - accuracy: 0.5323 - val_loss: 1.2821 - val_accuracy: 0.6188
Epoch 6/200
175341/175341 [==============================] - 51s 288us/step - loss: 1.3600 - accuracy: 0.5335 - val_loss: 1.2676 - val_accuracy: 0.6190
Epoch 7/200
175341/175341 [=========

Epoch 53/200
175341/175341 [==============================] - 51s 291us/step - loss: 1.1537 - accuracy: 0.5916 - val_loss: 1.1650 - val_accuracy: 0.6481
Epoch 54/200
175341/175341 [==============================] - 51s 290us/step - loss: 1.1508 - accuracy: 0.5919 - val_loss: 1.2078 - val_accuracy: 0.6155
Epoch 55/200
175341/175341 [==============================] - 51s 289us/step - loss: 1.1518 - accuracy: 0.5919 - val_loss: 1.1790 - val_accuracy: 0.6404
Epoch 56/200
175341/175341 [==============================] - 50s 287us/step - loss: 1.1514 - accuracy: 0.5923 - val_loss: 1.1728 - val_accuracy: 0.6455
Epoch 57/200
175341/175341 [==============================] - 51s 292us/step - loss: 1.1514 - accuracy: 0.5921 - val_loss: 1.1798 - val_accuracy: 0.6443
Epoch 58/200
175341/175341 [==============================] - 52s 298us/step - loss: 1.1520 - accuracy: 0.5914 - val_loss: 1.1905 - val_accuracy: 0.6210
Epoch 59/200
175341/175341 [==============================] - 52s 299us/step - los

175341/175341 [==============================] - 50s 286us/step - loss: 1.1417 - accuracy: 0.5921 - val_loss: 1.1963 - val_accuracy: 0.6235
Epoch 107/200
175341/175341 [==============================] - 52s 296us/step - loss: 1.1406 - accuracy: 0.5916 - val_loss: 1.1691 - val_accuracy: 0.6449
Epoch 108/200
175341/175341 [==============================] - 50s 284us/step - loss: 1.1408 - accuracy: 0.5930 - val_loss: 1.1835 - val_accuracy: 0.6409
Epoch 109/200
175341/175341 [==============================] - 51s 292us/step - loss: 1.1395 - accuracy: 0.5928 - val_loss: 1.1793 - val_accuracy: 0.6430
Epoch 110/200
175341/175341 [==============================] - 52s 299us/step - loss: 1.1400 - accuracy: 0.5931 - val_loss: 1.1826 - val_accuracy: 0.6421
Epoch 111/200
175341/175341 [==============================] - 51s 290us/step - loss: 1.1404 - accuracy: 0.5929 - val_loss: 1.2182 - val_accuracy: 0.6310
Epoch 112/200
175341/175341 [==============================] - 52s 295us/step - loss: 1.14

175341/175341 [==============================] - 49s 280us/step - loss: 1.1352 - accuracy: 0.5934 - val_loss: 1.2022 - val_accuracy: 0.6222
Epoch 160/200
175341/175341 [==============================] - 47s 267us/step - loss: 1.1358 - accuracy: 0.5933 - val_loss: 1.2136 - val_accuracy: 0.6162
Epoch 161/200
175341/175341 [==============================] - 47s 269us/step - loss: 1.1331 - accuracy: 0.5943 - val_loss: 1.1876 - val_accuracy: 0.6314
Epoch 162/200
175341/175341 [==============================] - 49s 281us/step - loss: 1.1357 - accuracy: 0.5946 - val_loss: 1.1901 - val_accuracy: 0.6246
Epoch 163/200
175341/175341 [==============================] - 46s 265us/step - loss: 1.1350 - accuracy: 0.5942 - val_loss: 1.2107 - val_accuracy: 0.6193
Epoch 164/200
175341/175341 [==============================] - 46s 264us/step - loss: 1.1335 - accuracy: 0.5946 - val_loss: 1.1868 - val_accuracy: 0.6290
Epoch 165/200
175341/175341 [==============================] - 48s 275us/step - loss: 1.13

In [21]:
from sklearn.metrics import accuracy_score
predictions = model.predict([xdelta1])
print(predictions[:5])

[[0.03368428 0.03462839 0.24563344 0.36159346 0.16308738 0.00300522
  0.05135835 0.08847929 0.01806662 0.00046367]
 [0.03367553 0.03532544 0.2504449  0.37808135 0.16750422 0.00061064
  0.03841875 0.07542875 0.02007264 0.00043773]
 [0.03370727 0.03518355 0.24947913 0.374226   0.16648316 0.00091572
  0.0414     0.0786015  0.01955903 0.00044463]
 [0.03371622 0.03510872 0.2489662  0.37232676 0.16597869 0.0011098
  0.04288625 0.08014288 0.01931667 0.00044785]
 [0.03366456 0.03535938 0.25067428 0.37906432 0.16776522 0.00054887
  0.03766744 0.07461137 0.02020862 0.0004359 ]]


In [33]:
import sys
np.set_printoptions(threshold=sys.maxsize)
#pred = np.zeros((82332,1), dtype=int)
for i in range(0, predictions.shape[0]):
    pred = np.where(predictions[i] == np.amax(predictions[i]))
    for j in range(1,10):
        predictions[i,j] = 0
    predictions[i,pred]=1
    
print(predictions[:5])

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [35]:
print("Accuracy: ",accuracy_score(y,predictions))
from sklearn.metrics import multilabel_confusion_matrix,classification_report,confusion_matrix
print("Classification Report: \n",classification_report(y,predictions))
conmat = np.array(confusion_matrix(y.argmax(axis=1), predictions.argmax(axis=1)))
confusion = pd.DataFrame(conmat, index=['0','1','2','3','4','5','6','7','8','9'],
                        columns=[['0','1','2','3','4','5','6','7','8','9']])
print (conmat)
conmat.shape

Accuracy:  0.6311640674342904
Classification Report: 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       677
           1       0.00      0.00      0.00       583
           2       0.36      0.00      0.00      4089
           3       0.23      0.37      0.29     11132
           4       0.42      0.00      0.01      6062
           5       0.84      0.96      0.89     18871
           6       0.69      0.80      0.74     37000
           7       0.00      0.00      0.00      3496
           8       0.00      0.00      0.00       378
           9       0.00      0.00      0.00        44

   micro avg       0.63      0.63      0.63     82332
   macro avg       0.25      0.21      0.19     82332
weighted avg       0.58      0.63      0.58     82332
 samples avg       0.63      0.63      0.63     82332

[[    0     0     2   622     0     2    51     0     0     0]
 [    0     0     2   528     0     6    47     0     0     0]
 [    

(10, 10)