In [2]:
from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Lambda
from keras.layers import Embedding
from keras.layers import Convolution1D,MaxPooling1D, Flatten
from keras.datasets import imdb
from keras import backend as K
from sklearn.model_selection import train_test_split
import pandas as pd
from keras.utils.np_utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from keras.models import Sequential
from keras.layers import Convolution1D, Dense, Dropout, Flatten, MaxPooling1D
from keras.utils import np_utils
import numpy as np
import h5py
from keras import callbacks
from keras.layers import LSTM, GRU, SimpleRNN, Bidirectional
from keras.callbacks import CSVLogger
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger

In [3]:
traindata = pd.read_csv('/home/ritika/NetworkIntrusionDetection/UNSW-NB15 - CSV Files/a part of training and testing set/UNSW_NB15_training-set.csv')
testdata = pd.read_csv('/home/ritika/NetworkIntrusionDetection/UNSW-NB15 - CSV Files/a part of training and testing set/UNSW_NB15_testing-set.csv')

#traindata=traindata.drop('id',axis=1)
#testdata=testdata.drop('id',axis=1)

from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()

traindata['proto'] = lb_make.fit_transform(traindata['proto'])
traindata['service'] = lb_make.fit_transform(traindata['service'])
traindata['state'] = lb_make.fit_transform(traindata['state'])
traindata['attack_cat'] = lb_make.fit_transform(traindata['attack_cat'])

testdata['proto'] = lb_make.fit_transform(testdata['proto'])
testdata['service'] = lb_make.fit_transform(testdata['service'])
testdata['state'] = lb_make.fit_transform(testdata['state'])
testdata['attack_cat'] = lb_make.fit_transform(testdata['attack_cat'])

X = traindata.iloc[:,1:42]
Y = traindata.iloc[:,-2]
x = testdata.iloc[:,1:42]
y = testdata.iloc[:,-2]

In [ ]:
Arr = X.values
arr = x.values

import librosa
Arr_Delta = librosa.feature.delta(Arr)
arr_delta = librosa.feature.delta(arr)

Delta = librosa.feature.delta(Arr_Delta)
delta = librosa.feature.delta(arr_delta)

Delta1 = pd.DataFrame(Arr_Delta)
delta1 = pd.DataFrame(arr_delta)
Delta2 = pd.DataFrame(Delta)
delta2 = pd.DataFrame(delta)

XDelta1 = pd.concat([X, Delta1, Delta2], axis=1)
xdelta1 = pd.concat([x, delta1, delta2], axis=1)

scaler = Normalizer().fit(XDelta1)
XDelta1 = scaler.transform(XDelta1)
scaler = Normalizer().fit(xdelta1)
xdelta1 = scaler.transform(xdelta1)

Y = np.array(Y)
y = np.array(y)

XDelta1 = np.reshape(XDelta1, (XDelta1.shape[0],XDelta1.shape[1],1))
xdelta1 = np.reshape(xdelta1, (xdelta1.shape[0],xdelta1.shape[1],1))

In [7]:
Y = to_categorical(Y)
y = to_categorical(y)

In [8]:
cnn = Sequential()
cnn.add(Convolution1D(64, 3, border_mode="same",activation="relu",input_shape=(123, 1)))
cnn.add(MaxPooling1D(pool_length=(2)))
cnn.add(Flatten())
cnn.add(Dense(128, activation="relu"))
cnn.add(Dropout(0.5))
cnn.add(Dense(10, activation="softmax"))
cnn.compile(loss="categorical_crossentropy", optimizer="adam",metrics=['accuracy'])
cnn.summary()   

/home/ritika/.virtualenvs/pythree/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(64, 3, activation="relu", input_shape=(123, 1), padding="same")`
  
/home/ritika/.virtualenvs/pythree/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `MaxPooling1D` call to the Keras 2 API: `MaxPooling1D(pool_size=2)`
  This is separate from the ipykernel package so we can avoid doing imports until


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_2 (Conv1D)            (None, 123, 64)           256       
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 61, 64)            0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 3904)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 128)               499840    
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                1290      
Total params: 501,386
Trainable params: 501,386
Non-trainable params: 0
________________________________________________

In [9]:
cnn.fit(XDelta1, Y, epochs=200, validation_data=(xdelta1, y))


Train on 175341 samples, validate on 82332 samples
Epoch 1/200
175341/175341 [==============================] - 181s 1ms/step - loss: 1.3918 - accuracy: 0.5302 - val_loss: 1.2832 - val_accuracy: 0.6179
Epoch 2/200
175341/175341 [==============================] - 188s 1ms/step - loss: 1.3455 - accuracy: 0.5353 - val_loss: 1.2780 - val_accuracy: 0.6185
Epoch 3/200
175341/175341 [==============================] - 185s 1ms/step - loss: 1.3357 - accuracy: 0.5404 - val_loss: 1.2825 - val_accuracy: 0.5978
Epoch 4/200
175341/175341 [==============================] - 203s 1ms/step - loss: 1.3298 - accuracy: 0.5430 - val_loss: 1.2731 - val_accuracy: 0.6005
Epoch 5/200
175341/175341 [==============================] - 215s 1ms/step - loss: 1.3263 - accuracy: 0.5431 - val_loss: 1.2823 - val_accuracy: 0.5919
Epoch 6/200
175341/175341 [==============================] - 189s 1ms/step - loss: 1.3242 - accuracy: 0.5452 - val_loss: 1.2729 - val_accuracy: 0.5977
Epoch 7/200
175341/175341 [===============

175341/175341 [==============================] - 166s 947us/step - loss: 1.3075 - accuracy: 0.5510 - val_loss: 1.2784 - val_accuracy: 0.5843
Epoch 54/200
175341/175341 [==============================] - 160s 913us/step - loss: 1.3078 - accuracy: 0.5508 - val_loss: 1.2821 - val_accuracy: 0.5899
Epoch 55/200
175341/175341 [==============================] - 162s 924us/step - loss: 1.3078 - accuracy: 0.5511 - val_loss: 1.2807 - val_accuracy: 0.5898
Epoch 56/200
175341/175341 [==============================] - 164s 936us/step - loss: 1.3082 - accuracy: 0.5511 - val_loss: 1.2772 - val_accuracy: 0.5884
Epoch 57/200
175341/175341 [==============================] - 167s 955us/step - loss: 1.3073 - accuracy: 0.5509 - val_loss: 1.2663 - val_accuracy: 0.5918
Epoch 58/200
175341/175341 [==============================] - 178s 1ms/step - loss: 1.3069 - accuracy: 0.5503 - val_loss: 1.2738 - val_accuracy: 0.5858
Epoch 59/200
175341/175341 [==============================] - 172s 981us/step - loss: 1.306

175341/175341 [==============================] - 152s 865us/step - loss: 1.2931 - accuracy: 0.5511 - val_loss: 1.2715 - val_accuracy: 0.5863
Epoch 107/200
175341/175341 [==============================] - 152s 868us/step - loss: 1.2919 - accuracy: 0.5503 - val_loss: 1.2787 - val_accuracy: 0.5830
Epoch 108/200
175341/175341 [==============================] - 152s 869us/step - loss: 1.2920 - accuracy: 0.5512 - val_loss: 1.2674 - val_accuracy: 0.5908
Epoch 109/200
175341/175341 [==============================] - 148s 845us/step - loss: 1.2915 - accuracy: 0.5502 - val_loss: 1.2834 - val_accuracy: 0.5726
Epoch 110/200
175341/175341 [==============================] - 153s 872us/step - loss: 1.2923 - accuracy: 0.5508 - val_loss: 1.2735 - val_accuracy: 0.5654
Epoch 111/200
175341/175341 [==============================] - 150s 856us/step - loss: 1.2914 - accuracy: 0.5514 - val_loss: 1.2634 - val_accuracy: 0.5824
Epoch 112/200
175341/175341 [==============================] - 150s 855us/step - los

Epoch 159/200
175341/175341 [==============================] - 162s 923us/step - loss: 1.2881 - accuracy: 0.5497 - val_loss: 1.2844 - val_accuracy: 0.5622
Epoch 160/200
175341/175341 [==============================] - 161s 919us/step - loss: 1.2886 - accuracy: 0.5494 - val_loss: 1.2740 - val_accuracy: 0.5745
Epoch 161/200
175341/175341 [==============================] - 159s 905us/step - loss: 1.2870 - accuracy: 0.5500 - val_loss: 1.2923 - val_accuracy: 0.5413
Epoch 162/200
175341/175341 [==============================] - 162s 924us/step - loss: 1.2884 - accuracy: 0.5502 - val_loss: 1.2726 - val_accuracy: 0.5830
Epoch 163/200
175341/175341 [==============================] - 153s 870us/step - loss: 1.2869 - accuracy: 0.5495 - val_loss: 1.2636 - val_accuracy: 0.5911
Epoch 164/200
175341/175341 [==============================] - 161s 920us/step - loss: 1.2876 - accuracy: 0.5506 - val_loss: 1.2598 - val_accuracy: 0.5921
Epoch 165/200
175341/175341 [==============================] - 161s 91

In [11]:
from sklearn.metrics import accuracy_score
predictions = cnn.predict([xdelta1])

import sys
np.set_printoptions(threshold=sys.maxsize)
#pred = np.zeros((82332,1), dtype=int)
for i in range(0, predictions.shape[0]):
    pred = np.where(predictions[i] == np.amax(predictions[i]))
    for j in range(0,10):
        predictions[i,j] = 0
    predictions[i,pred]=1
    
print(predictions[:5])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [12]:
print("Accuracy: ",accuracy_score(y,predictions))
from sklearn.metrics import multilabel_confusion_matrix,classification_report,confusion_matrix
print("Classification Report: \n",classification_report(y,predictions))
conmat = np.array(confusion_matrix(y.argmax(axis=1), predictions.argmax(axis=1)))
confusion = pd.DataFrame(conmat, index=['0','1','2','3','4','5','6','7','8','9'],
                        columns=[['0','1','2','3','4','5','6','7','8','9']])
print (conmat)
conmat.shape

Accuracy:  0.5872078900063159


/home/ritika/.virtualenvs/pythree/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Classification Report: 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       677
           1       0.33      0.00      0.01       583
           2       0.79      0.01      0.01      4089
           3       0.28      0.33      0.30     11132
           4       0.46      0.01      0.01      6062
           5       0.55      0.97      0.70     18871
           6       0.74      0.71      0.73     37000
           7       0.00      0.00      0.00      3496
           8       0.00      0.00      0.00       378
           9       0.00      0.00      0.00        44

   micro avg       0.59      0.59      0.59     82332
   macro avg       0.31      0.20      0.18     82332
weighted avg       0.57      0.59      0.53     82332
 samples avg       0.59      0.59      0.59     82332

[[    0     0     0    45     0   602    30     0     0     0]
 [    0     2     0    63     0   486    32     0     0     0]
 [    0     0    22   756     7  264

(10, 10)