In [2]:
from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Lambda
from keras.layers import Embedding
from keras.layers import Convolution1D,MaxPooling1D, Flatten
from keras.datasets import imdb
from keras import backend as K
from sklearn.model_selection import train_test_split
import pandas as pd
from keras.utils.np_utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from keras.models import Sequential
from keras.layers import Convolution1D, Dense, Dropout, Flatten, MaxPooling1D
from keras.utils import np_utils
import numpy as np
import h5py
from keras import callbacks
from keras.layers import LSTM, GRU, SimpleRNN, Bidirectional
from keras.callbacks import CSVLogger
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau, CSVLogger

In [3]:
traindata = pd.read_csv('/home/ritika/NetworkIntrusionDetection/UNSW-NB15 - CSV Files/a part of training and testing set/UNSW_NB15_training-set.csv')
testdata = pd.read_csv('/home/ritika/NetworkIntrusionDetection/UNSW-NB15 - CSV Files/a part of training and testing set/UNSW_NB15_testing-set.csv')

#traindata=traindata.drop('id',axis=1)
#testdata=testdata.drop('id',axis=1)

from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()

traindata['proto'] = lb_make.fit_transform(traindata['proto'])
traindata['service'] = lb_make.fit_transform(traindata['service'])
traindata['state'] = lb_make.fit_transform(traindata['state'])
traindata['attack_cat'] = lb_make.fit_transform(traindata['attack_cat'])

testdata['proto'] = lb_make.fit_transform(testdata['proto'])
testdata['service'] = lb_make.fit_transform(testdata['service'])
testdata['state'] = lb_make.fit_transform(testdata['state'])
testdata['attack_cat'] = lb_make.fit_transform(testdata['attack_cat'])

X = traindata.iloc[:,1:42]
Y = traindata.iloc[:,-2]
x = testdata.iloc[:,1:42]
y = testdata.iloc[:,-2]

In [4]:
Arr = X.values
arr = x.values

import librosa
Arr_Delta = librosa.feature.delta(Arr)
arr_delta = librosa.feature.delta(arr)

Delta = librosa.feature.delta(Arr_Delta)
delta = librosa.feature.delta(arr_delta)

Delta1 = pd.DataFrame(Arr_Delta)
delta1 = pd.DataFrame(arr_delta)
Delta2 = pd.DataFrame(Delta)
delta2 = pd.DataFrame(delta)

XDelta1 = pd.concat([X, Delta1, Delta2], axis=1)
xdelta1 = pd.concat([x, delta1, delta2], axis=1)

scaler = Normalizer().fit(XDelta1)
XDelta1 = scaler.transform(XDelta1)
scaler = Normalizer().fit(xdelta1)
xdelta1 = scaler.transform(xdelta1)

Y = np.array(Y)
y = np.array(y)

XDelta1 = np.reshape(XDelta1, (XDelta1.shape[0],1,XDelta1.shape[1]))
xdelta1 = np.reshape(xdelta1, (xdelta1.shape[0],1,xdelta1.shape[1]))

In [8]:
Y = to_categorical(Y)
y = to_categorical(y)

In [9]:
model = Sequential()
model.add(LSTM(4,input_dim=123)) 
model.add(Dropout(0.1))
model.add(Dense(10))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

/home/ritika/.virtualenvs/pythree/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
  
/home/ritika/.virtualenvs/pythree/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(4, input_shape=(None, 123...)`
  


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 4)                 2048      
_________________________________________________________________
dropout_3 (Dropout)          (None, 4)                 0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                50        
_________________________________________________________________
activation_3 (Activation)    (None, 10)                0         
Total params: 2,098
Trainable params: 2,098
Non-trainable params: 0
_________________________________________________________________


In [10]:
history = model.fit(XDelta1, Y, epochs=200, validation_data=(xdelta1, y))


Train on 175341 samples, validate on 82332 samples
Epoch 1/200
175341/175341 [==============================] - 46s 264us/step - loss: 1.4899 - accuracy: 0.5206 - val_loss: 1.2993 - val_accuracy: 0.6175
Epoch 2/200
175341/175341 [==============================] - 48s 276us/step - loss: 1.3984 - accuracy: 0.5276 - val_loss: 1.2922 - val_accuracy: 0.6175
Epoch 3/200
175341/175341 [==============================] - 53s 301us/step - loss: 1.3862 - accuracy: 0.5292 - val_loss: 1.2962 - val_accuracy: 0.6181
Epoch 4/200
175341/175341 [==============================] - 48s 271us/step - loss: 1.3743 - accuracy: 0.5322 - val_loss: 1.2925 - val_accuracy: 0.6187
Epoch 5/200
175341/175341 [==============================] - 50s 283us/step - loss: 1.3646 - accuracy: 0.5325 - val_loss: 1.2784 - val_accuracy: 0.6189
Epoch 6/200
175341/175341 [==============================] - 48s 274us/step - loss: 1.3542 - accuracy: 0.5330 - val_loss: 1.2704 - val_accuracy: 0.6192
Epoch 7/200
175341/175341 [=========

Epoch 53/200
175341/175341 [==============================] - 51s 290us/step - loss: 1.1572 - accuracy: 0.5965 - val_loss: 1.2043 - val_accuracy: 0.6441
Epoch 54/200
175341/175341 [==============================] - 54s 306us/step - loss: 1.1578 - accuracy: 0.5962 - val_loss: 1.2051 - val_accuracy: 0.6440
Epoch 55/200
175341/175341 [==============================] - 51s 291us/step - loss: 1.1575 - accuracy: 0.5959 - val_loss: 1.2154 - val_accuracy: 0.6306
Epoch 56/200
175341/175341 [==============================] - 55s 313us/step - loss: 1.1563 - accuracy: 0.5962 - val_loss: 1.2022 - val_accuracy: 0.6440
Epoch 57/200
175341/175341 [==============================] - 49s 280us/step - loss: 1.1558 - accuracy: 0.5958 - val_loss: 1.2031 - val_accuracy: 0.6438
Epoch 58/200
175341/175341 [==============================] - 50s 285us/step - loss: 1.1555 - accuracy: 0.5952 - val_loss: 1.2139 - val_accuracy: 0.6366
Epoch 59/200
175341/175341 [==============================] - 49s 277us/step - los

175341/175341 [==============================] - 54s 310us/step - loss: 1.1417 - accuracy: 0.5970 - val_loss: 1.2304 - val_accuracy: 0.5304
Epoch 107/200
175341/175341 [==============================] - 53s 301us/step - loss: 1.1417 - accuracy: 0.5971 - val_loss: 1.2258 - val_accuracy: 0.5305
Epoch 108/200
175341/175341 [==============================] - 56s 321us/step - loss: 1.1425 - accuracy: 0.5970 - val_loss: 1.1901 - val_accuracy: 0.6378
Epoch 109/200
175341/175341 [==============================] - 55s 314us/step - loss: 1.1415 - accuracy: 0.5968 - val_loss: 1.1871 - val_accuracy: 0.6354
Epoch 110/200
175341/175341 [==============================] - 54s 310us/step - loss: 1.1412 - accuracy: 0.5969 - val_loss: 1.1874 - val_accuracy: 0.6470
Epoch 111/200
175341/175341 [==============================] - 51s 288us/step - loss: 1.1398 - accuracy: 0.5973 - val_loss: 1.2124 - val_accuracy: 0.6261
Epoch 112/200
175341/175341 [==============================] - 54s 306us/step - loss: 1.14

175341/175341 [==============================] - 54s 309us/step - loss: 1.1360 - accuracy: 0.5978 - val_loss: 1.2094 - val_accuracy: 0.6197
Epoch 160/200
175341/175341 [==============================] - 51s 293us/step - loss: 1.1362 - accuracy: 0.5977 - val_loss: 1.1823 - val_accuracy: 0.6385
Epoch 161/200
175341/175341 [==============================] - 50s 286us/step - loss: 1.1359 - accuracy: 0.5975 - val_loss: 1.1791 - val_accuracy: 0.6399
Epoch 162/200
175341/175341 [==============================] - 50s 285us/step - loss: 1.1363 - accuracy: 0.5974 - val_loss: 1.1887 - val_accuracy: 0.6345
Epoch 163/200
175341/175341 [==============================] - 53s 303us/step - loss: 1.1372 - accuracy: 0.5976 - val_loss: 1.1777 - val_accuracy: 0.6438
Epoch 164/200
175341/175341 [==============================] - 52s 295us/step - loss: 1.1355 - accuracy: 0.5971 - val_loss: 1.2029 - val_accuracy: 0.6292
Epoch 165/200
175341/175341 [==============================] - 54s 306us/step - loss: 1.13

In [11]:
from sklearn.metrics import accuracy_score
predictions = model.predict([xdelta1])

import sys
np.set_printoptions(threshold=sys.maxsize)
#pred = np.zeros((82332,1), dtype=int)
for i in range(0, predictions.shape[0]):
    pred = np.where(predictions[i] == np.amax(predictions[i]))
    for j in range(0,10):
        predictions[i,j] = 0
    predictions[i,pred]=1
    
print(predictions[:5])

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [12]:
print("Accuracy: ",accuracy_score(y,predictions))
from sklearn.metrics import multilabel_confusion_matrix,classification_report,confusion_matrix
print("Classification Report: \n",classification_report(y,predictions))
conmat = np.array(confusion_matrix(y.argmax(axis=1), predictions.argmax(axis=1)))
confusion = pd.DataFrame(conmat, index=['0','1','2','3','4','5','6','7','8','9'],
                        columns=[['0','1','2','3','4','5','6','7','8','9']])
print (conmat)
conmat.shape

Accuracy:  0.6244595054170917


/home/ritika/.virtualenvs/pythree/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Classification Report: 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       677
           1       0.00      0.00      0.00       583
           2       0.26      0.00      0.01      4089
           3       0.23      0.39      0.29     11132
           4       0.43      0.00      0.01      6062
           5       0.84      0.96      0.89     18871
           6       0.70      0.78      0.74     37000
           7       0.00      0.00      0.00      3496
           8       0.00      0.00      0.00       378
           9       0.00      0.00      0.00        44

   micro avg       0.62      0.62      0.62     82332
   macro avg       0.25      0.21      0.19     82332
weighted avg       0.58      0.62      0.58     82332
 samples avg       0.62      0.62      0.62     82332

[[    0     0     0   629     0     2    46     0     0     0]
 [    0     0     2   533     2     5    41     0     0     0]
 [    0     0    11  3044     7   13

(10, 10)